[package]
name = "manufactory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.18"
winit = "0.28"
bytemuck = { version = "1.13.1", features = ["derive"] }
image = "0.24.6"
nalgebra-glm = "0.18.0"
bitflags = "2.3.3"
rand = "0.8.5"
itertools = "0.11.0"
atomic-wait = "1.1.0"
tokio = { version = "1.34.0", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

rodio = "0.17.3"

flate2 = "1.0.28"

egui_wgpu_backend = "0.27"
egui = { version = "0.23", features = ["color-hex"]}
egui_winit_platform = "0.20"

russimp = { version = "=2.0.5", features = ["prebuilt"] }

[profile.dev]
opt-level = 1
debug = true

[profile.release]
debug = true

[profile.full-release]
inherits = "release"
opt-level = 3
codegen-units = 1
debug = false
lto = "fat"
strip = "symbols"