[package]
name = "p1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "*"
winit = "*"
async-std = "*"
bytemuck = { version = "1.13.1", features = ["derive"] }
image = "0.24.6"
anyhow = "1.0.71"
cgmath = "0.18"
nalgebra-glm = "0.18.0"
bitflags = "2.3.3"


[profile.dev]
opt-level = 1

[profile.release]
opt-level = 1