[package]
name = "graphics_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu-core = "0.19.0"
wgpu-types = { version = "0.19", features = ["serde", "trace", "replay"]}
wgpu = "0.19"

winit = "0.29"
bytemuck = { version = "1.14", features = ["derive"] }
image = "0.24.6"
itertools = "0.11.0"
rayon = "1.8"
serde = "1"

egui-winit = "0.26.0"
egui-wgpu = "0.26"
egui = { version = "0.26", features = ["color-hex"]}

walkdir = "2"

nalgebra-glm = { version = "0.18.0", features = ["convert-bytemuck"] }
russimp = { version = "=2.0.5", features = ["prebuilt"] }