use crate::voxels::block::{block_test::{Block, BlockBase}, block_type::BlockType, functions::{on_break, player_add_item}};


#[derive(Debug)]
pub struct Content {
    pub blocks: Vec<Block>
}

impl Content {
    pub fn new() -> Self {
        Self {
            blocks: vec![
                Block {
                    base: BlockBase {
                        id: 0,
                        item_id: Some(0),
                        block_type: BlockType::None,
                        depth: 1,
                        height: 1,
                        width: 1,
                        emission: [0, 0, 0],
                        is_additional_data: false,
                        is_light_passing: true,
                        is_glass: false,
                        is_ore: false,
                    },
                    on_block_break: Box::new([]),
                    on_block_set: Box::new([]),
                },
                Block {
                    base: BlockBase {
                        id: 1,
                        item_id: None,
                        block_type: BlockType::None,
                        depth: 1,
                        height: 1,
                        width: 1,
                        emission: [0, 0, 0],
                        is_additional_data: false,
                        is_light_passing: true,
                        is_glass: false,
                        is_ore: false,
                    },
                    on_block_break: Box::new([]),
                    on_block_set: Box::new([]),
                },
                Block {
                    base: BlockBase {
                        id: 2,
                        item_id: None,
                        block_type: BlockType::Block { faces: [4, 4, 4, 4, 4, 4] },
                        depth: 1,
                        height: 1,
                        width: 1,
                        emission: [0, 0, 0],
                        is_additional_data: false,
                        is_light_passing: true,
                        is_glass: false,
                        is_ore: false,
                    },
                    on_block_break: Box::new([]),
                    on_block_set: Box::new([]),
                },
                Block {
                    base: BlockBase {
                        id: 3,
                        item_id: None,
                        block_type: BlockType::Block { faces: [4, 4, 4, 4, 4, 4] },
                        depth: 1,
                        height: 1,
                        width: 1,
                        emission: [0, 0, 0],
                        is_additional_data: false,
                        is_light_passing: true,
                        is_glass: false,
                        is_ore: false,
                    },
                    on_block_break: Box::new([]),
                    on_block_set: Box::new([]),
                },
                Block {
                    base: BlockBase {
                        id: 4,
                        item_id: None,
                        block_type: BlockType::Block { faces: [4, 4, 4, 4, 4, 4] },
                        depth: 1,
                        height: 1,
                        width: 1,
                        emission: [0, 0, 0],
                        is_additional_data: false,
                        is_light_passing: true,
                        is_glass: false,
                        is_ore: false,
                    },
                    on_block_break: Box::new([]),
                    on_block_set: Box::new([]),
                },
                Block {
                    base: BlockBase {
                        id: 5,
                        item_id: None,
                        block_type: BlockType::Block { faces: [4, 4, 4, 4, 4, 4] },
                        depth: 1,
                        height: 1,
                        width: 1,
                        emission: [0, 0, 0],
                        is_additional_data: false,
                        is_light_passing: true,
                        is_glass: false,
                        is_ore: false,
                    },
                    on_block_break: Box::new([&on_break, &player_add_item]),
                    on_block_set: Box::new([]),
                },
                Block {
                    base: BlockBase {
                        id: 6,
                        item_id: None,
                        block_type: BlockType::Block { faces: [4, 4, 4, 4, 4, 4] },
                        depth: 1,
                        height: 1,
                        width: 1,
                        emission: [0, 0, 0],
                        is_additional_data: false,
                        is_light_passing: true,
                        is_glass: false,
                        is_ore: false,
                    },
                    on_block_break: Box::new([]),
                    on_block_set: Box::new([]),
                },
                Block {
                    base: BlockBase {
                        id: 7,
                        item_id: None,
                        block_type: BlockType::Block { faces: [4, 4, 4, 4, 4, 4] },
                        depth: 1,
                        height: 1,
                        width: 1,
                        emission: [0, 0, 0],
                        is_additional_data: false,
                        is_light_passing: true,
                        is_glass: false,
                        is_ore: false,
                    },
                    on_block_break: Box::new([]),
                    on_block_set: Box::new([]),
                },
                Block {
                    base: BlockBase {
                        id: 8,
                        item_id: None,
                        block_type: BlockType::Block { faces: [4, 4, 4, 4, 4, 4] },
                        depth: 1,
                        height: 1,
                        width: 1,
                        emission: [0, 0, 0],
                        is_additional_data: false,
                        is_light_passing: true,
                        is_glass: false,
                        is_ore: false,
                    },
                    on_block_break: Box::new([]),
                    on_block_set: Box::new([]),
                },
                Block {
                    base: BlockBase {
                        id: 9,
                        item_id: None,
                        block_type: BlockType::Block { faces: [4, 4, 4, 4, 4, 4] },
                        depth: 1,
                        height: 1,
                        width: 1,
                        emission: [0, 0, 0],
                        is_additional_data: false,
                        is_light_passing: true,
                        is_glass: false,
                        is_ore: false,
                    },
                    on_block_break: Box::new([]),
                    on_block_set: Box::new([]),
                },
                Block {
                    base: BlockBase {
                        id: 10,
                        item_id: Some(0),
                        block_type: BlockType::Block { faces: [4, 4, 4, 4, 4, 4] },
                        depth: 1,
                        height: 1,
                        width: 1,
                        emission: [0, 0, 0],
                        is_additional_data: false,
                        is_light_passing: true,
                        is_glass: false,
                        is_ore: false,
                    },
                    on_block_break: Box::new([]),
                    on_block_set: Box::new([]),
                },
            ]
        }
    }
}